Changing the time of day
mo3g666/project-x pull request #17
Opened 2022-01-10 19:56 UTC by exodie

Тестовый вариант

2022-01-12 19:27 UTC, mike-hammer commented on src/client/hud/browser.ts
> +mp.events.add("render", () => {
Render не самое лучшее место для этого)) Можно инициализировать обновление время в интерфейсе с сервера и рассылать его всем клиентам. Детализация по секундам нам прям не нужна, поэтому можно делать обновление каждую минуту. А клиент уже соответственное кидает его в CEF.

Также нужно предусмотреть на сервере ситуацию когда игрок только подключился и ему нужно кинуть текущее время.

2022-01-12 19:27 UTC, mike-hammer commented on src/server/time/index.ts
> +  let hour = +parts.find(x => x.type === 'hour')!.value // dts
Что здесь происходит?) Однострочники зло, т. к. другой человек который это не написал будет долго смотреть и чесать репу. Нам по сути нужно только узнать часы и минуты.

2022-01-12 19:27 UTC, mike-hammer commented on src/server/weather/index.ts
> +export const weatherType = [
Это код из другого pull request, он сюда не должен попасть, как и остальные дубли.

2022-01-12 19:42 UTC, mo3g666 commented on src/client/hud/browser.ts
> +mp.events.add("render", () => {
Полностью согласен, осуществлять callRemote из рендер функции приведет к крашу клиента или сервера. Так же этот файл не предназначен для функциональной нагрузки, а лишь как хранение экспортов для доступа к экземплярам браузеров.

2022-01-12 19:56 UTC, mo3g666 commented on src/server/time/index.ts
> +  let hour = +parts.find(x => x.type === 'hour')!.value // dts
Первое замечание это использование `let` там, где ты более не изменяешь значения, старайся использовать `const`. Второй момент связан с типом `any`. Если ты заранее знаешь какой структуры будет собираемый объект или массив, то лучше сделать для него интерфейс, что бы IDE могла подсказать, что от него ожидать.  Так же рекомендую всё-таки перенести интервал на сторону клиента и использовать конструктор Date() с получением данных через UTC методы и выставлением времени, а корректировку уже проводить с сервера.

2022-01-12 20:09 UTC, mo3g666 requested changes
Многие файлы не соответствуют конифгурации prettier и eslint

2022-01-12 20:09 UTC, mo3g666 commented on src/client/index.ts
> +import "./hud/browser"
Этому здесь не место, так как импорт браузеров происходит только по необходимости, но не в корневом файле

2022-01-12 20:09 UTC, mo3g666 commented on src/server/weather/index.ts
> +})
Не реализовано динамическое смешивание погодных условий, в данном решении невозможна погода совмещающая в себе несколько типов на продолжительное время

2022-01-12 20:09 UTC, mo3g666 commented on src/server/weather/index.ts
> +        })()
Кажется нужно пересмотреть эту `само вызываемую` функцию в интервале

2022-01-13 06:35 UTC, mike-hammer commented on src/server/weather/index.ts
> +})
@mo3g666 можешь скинуть пример подобного смешивания или функцию с wiki?

2022-01-14 09:31 UTC, mo3g666 commented on src/server/weather/index.ts
> +})
@mike-hammer 
https://wiki.rage.mp/index.php?title=Gameplay::setWeatherTypeTransition

2022-06-02 09:06 UTC, closed without merging